---

- name: Prep
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      tags: prepare
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

- name: Base role
  hosts: all
  become: yes
  roles:
    - role: "base"
      tags: [ base ]

- name: Interactive role
  hosts: interactive,workstations,laptops
  become: yes
  roles:
    - role: "interactive"
      tags: [ interactive ]

- name: Workstation role
  hosts: workstations,laptops
  become: yes
  become_user: "{{ gui_user.name }}"
  roles:
    - role: haxwithaxe.warpd
      tags: [ workstation, warpd ]
    - role: "workstation"
      tags: [ workstation ]

- name: Laptop role
  hosts: laptops
  become: yes
  become_user: "{{ gui_user.name }}"
  roles:
    - role: "laptop"
      tags: [ laptop ]
