---

force_bash: no
force_bash_completion: no
force_ntfyr: no
force_psrc: no
force_neovim: no
force_vim: no
force_vim_plugins: no


device_type: "noninteractive"

users: 
  - name: "hax"
    home_dir: "/home/hax"
  - name: "root"
    home_dir: "/root"


