---

- name: Ensure important directories exist
  tags: always
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ user.home_dir }}/.config"
    - "{{ user.home_dir }}/.local"
    - "{{ user.home_dir }}/.psrc.d"
    - "{{ user.home_dir }}/.bash_aliases.d"
    - "{{ user.home_dir }}/.bash_completion.d"
    - "{{ user.home_dir }}/.bashrc.d"
    - "{{ user.home_dir }}/.config/nvim"
    - "{{ user.home_dir }}/.vim"

- name: Install vim config
  tags: install,config,dependency,javascript,neovim,plugins,python,syntax,vim
  include_tasks: 
    file: "tasks/vim.yml"
    apply:
      tags: [ vim, neovim ]

- name: Install black config
  tags: install,config,python,syntax
  copy:
    src: files/black
    dest: "{{ user.home_dir }}/.config/black"

- name: Install interactive .bash_aliases.d files
  tags: bash,bash_aliases,install
  copy:
    src: "files/bash_aliases/{{ item }}"
    dest: "{{ user.home_dir }}/.bash_aliases.d/{{ item }}"
  with_items:
    - df-to-duf

- name: Install interactive .bashrc.d files
  tags: bash,bashrc,install
  copy:
    src: "files/bashrc/{{ item }}"
    dest: "{{ user.home_dir }}/.bashrc.d/{{ item }}"
  with_items:
    - liquidprompt

- name: Ensure liquidpromt config directories exists
  tags: liquidpromt,config,theme
  ansible.builtin.file:
    path: "{{ user.home_dir }}/.config/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0750'
  loop:
    - liquidpromt
    - liquidpromt/themes
    - liquidpromt/themes/folded

- name: Install liqidpromtrc
  tags: liquidpromt,config
  copy:
    src: "files/liquidpromptrc"
    dest: "{{ user.home_dir }}/.config/liquidpromptrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0640'

- name: Install liquidpromt folded theme
  tags: liquidpromt,config,theme
  ansible.builtin.copy:
    src: "files/liquidprompt/themes/folded/folded.theme"
    dest: "{{ user.home_dir }}/.config/liquidprompt/themes/folded/folded.theme"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0640'
