---

- name: nodm_enable_start
  become_user: root # role is run as non-root user
  service:
    name: nodm.service
    enabled: yes
    state: started

- name: greetd_restart
  become_user: root # role is run as non-root user
  service:
    name: greetd.service
    enabled: yes
    state: restarted
