---

- name: Set force variables if global force
  tags: always
  set_fact:
    force_bash: yes
    force_bash_completion: yes
    force_neovim: yes
    force_vim: yes
    force_vim_plugins: yes
  when: force | default(false) | bool


- name: Setup prerequisits
  tags: alert,bash,bash_completion,install,prepare,python
  include_tasks:
    file: "tasks/pre.yml"
    apply:
      tags: [ install, prepare ]

- name: Setup dotfiles for each user
  tags: alert,bash,bash_aliases,bash_completion,bashrc,host_specific,install,neovim,plugins,profile,psrc,python,vim,vimrc
  include_tasks: "tasks/user.yml"
  args:
    apply:
      become_user: "{{ user.name }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
